export type ReadingMode = 'mushaf' | 'tafseer' | 'meanings' | 'translation';

export const JUZ_MAP = [{j:1,s:1,a:1},{j:2,s:2,a:142},{j:3,s:2,a:253},{j:4,s:3,a:93},{j:5,s:4,a:24},{j:6,s:4,a:148},{j:7,s:5,a:82},{j:8,s:6,a:111},{j:9,s:7,a:88},{j:10,s:8,a:41},{j:11,s:9,a:93},{j:12,s:11,a:6},{j:13,s:12,a:53},{j:14,s:15,a:1},{j:15,s:17,a:1},{j:16,s:18,a:75},{j:17,s:21,a:1},{j:18,s:23,a:1},{j:19,s:25,a:21},{j:20,s:27,a:56},{j:21,s:29,a:46},{j:22,s:33,a:31},{j:23,s:36,a:28},{j:24,s:39,a:32},{j:25,s:41,a:47},{j:26,s:46,a:1},{j:27,s:51,a:31},{j:28,s:58,a:1},{j:29,s:67,a:1},{j:30,s:78,a:1}];

export const HIZB_QUARTERS = [1,1,20,31,43,51,61,71,75,83,88,94,99,102,105,107,113,117,122,125,129,133,137,140,144,147,151,154,159,162,164,165,167,171,174,176,178,181,183,187,190,193,196,198,199,201,202,204,206,207,208,209,210,211,213,214,215,217,218,219,220,221,221,222,223,224,225,226,227,227,228,229,229,230,231,231,232,233,233,234,234,235,235,236,236,236,237,237,237,238,238,238,238,239,239,239,239,239,239,239,240,240,240,240,240,240,240,240,240,240,240,240,240,240];

export const SAJDAH_LOCATIONS = [{s:7, a:206}, {s:13, a:15}, {s:16, a:50}, {s:17, a:109}, {s:19, a:58}, {s:22, a:18}, {s:22, a:77}, {s:25, a:60}, {s:27, a:26}, {s:32, a:15}, {s:38, a:24}, {s:41, a:38}, {s:53, a:62}, {s:84, a:21}, {s:96, a:19}];
export const THEMES = {
    black: { id: "black", name: "افتراضي", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#000000", barBorder: "#000000", btnBg: "#ffffff", btnText: "#000000", accent: "#10b981", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#000000", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#000000", sajdah: "#d97706", highlightText: "#10b981", verseBracket: "#d97706" },
    night_sky: { id: "night_sky", name: "أزرق", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#3b82f6", barBorder: "#3b82f6", btnBg: "#ffffff", btnText: "#3b82f6", accent: "#3b82f6", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#3b82f6", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#3b82f6", sajdah: "#d97706", highlightText: "#3b82f6", verseBracket: "#16a34a" },
    green: { id: "green", name: "أخضر", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#16a34a", barBorder: "#16a34a", btnBg: "#ffffff", btnText: "#16a34a", accent: "#16a34a", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#16a34a", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#16a34a", sajdah: "#d97706", highlightText: "#16a34a", verseBracket: "#d97706" },
    red: { id: "red", name: "أحمر", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#dc2626", barBorder: "#dc2626", btnBg: "#ffffff", btnText: "#dc2626", accent: "#dc2626", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#dc2626", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#dc2626", sajdah: "#d97706", highlightText: "#dc2626", verseBracket: "#2563eb" },
    maroon: { id: "maroon", name: "نبيتي", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#831843", barBorder: "#831843", btnBg: "#ffffff", btnText: "#831843", accent: "#831843", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#831843", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#831843", sajdah: "#d97706", highlightText: "#831843", verseBracket: "#16a34a" },
    olive: { id: "olive", name: "زيتوني", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#65a30d", barBorder: "#65a30d", btnBg: "#ffffff", btnText: "#65a30d", accent: "#65a30d", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#65a30d", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#65a30d", sajdah: "#d97706", highlightText: "#65a30d", verseBracket: "#831843" },
    blue: { id: "blue", name: "نيلي فاتح", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#4f46e5", barBorder: "#4f46e5", btnBg: "#ffffff", btnText: "#4f46e5", accent: "#4f46e5", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#4f46e5", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#4f46e5", sajdah: "#d97706", highlightText: "#4f46e5", verseBracket: "#ea580c" },
    brown: { id: "brown", name: "بني", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#92400e", barBorder: "#92400e", btnBg: "#ffffff", btnText: "#92400e", accent: "#92400e", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#92400e", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#92400e", sajdah: "#2563eb", highlightText: "#92400e", verseBracket: "#2563eb" },
    purple: { id: "purple", name: "بنفسجي", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#9333ea", barBorder: "#9333ea", btnBg: "#ffffff", btnText: "#9333ea", accent: "#9333ea", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#9333ea", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#9333ea", sajdah: "#d97706", highlightText: "#9333ea", verseBracket: "#16a34a" },
    orange: { id: "orange", name: "برتقالي", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#ea580c", barBorder: "#ea580c", btnBg: "#ffffff", btnText: "#ea580c", accent: "#ea580c", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#ea580c", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#ea580c", sajdah: "#2563eb", highlightText: "#ea580c", verseBracket: "#2563eb" },
    sky: { id: "sky", name: "سماوي فاتح", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#0ea5e9", barBorder: "#0ea5e9", btnBg: "#ffffff", btnText: "#0ea5e9", accent: "#0ea5e9", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#0ea5e9", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#0ea5e9", sajdah: "#d97706", highlightText: "#0ea5e9", verseBracket: "#d97706" },
    amber_light: { id: "amber_light", name: "كهرماني", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#f59e0b", barBorder: "#f59e0b", btnBg: "#ffffff", btnText: "#f59e0b", accent: "#f59e0b", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#f59e0b", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#f59e0b", sajdah: "#d97706", highlightText: "#f59e0b", verseBracket: "#3b82f6" },
    mint: { id: "mint", name: "نعناعي", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#4ade80", barBorder: "#4ade80", btnBg: "#ffffff", btnText: "#4ade80", accent: "#4ade80", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#4ade80", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#4ade80", sajdah: "#d97706", highlightText: "#4ade80", verseBracket: "#dc2626" },
    pink: { id: "pink", name: "وردي", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#db2777", barBorder: "#db2777", btnBg: "#ffffff", btnText: "#db2777", accent: "#db2777", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#db2777", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#db2777", sajdah: "#d97706", highlightText: "#db2777", verseBracket: "#16a34a" },
    cyan: { id: "cyan", name: "سماوي", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#0891b2", barBorder: "#0891b2", btnBg: "#ffffff", btnText: "#0891b2", accent: "#0891b2", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#0891b2", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#0891b2", sajdah: "#d97706", highlightText: "#0891b2", verseBracket: "#d97706" },
    lime: { id: "lime", name: "ليموني", bg: "#ffffff", text: "#000000", font: "var(--font-amiri)", barBg: "#ffffff", barText: "#84cc16", barBorder: "#84cc16", btnBg: "#ffffff", btnText: "#84cc16", accent: "#84cc16", accentText: "#ffffff", modalBg: "#ffffff", modalText: "#000000", headerBg: "#ffffff", headerText: "#84cc16", cardBg: "#ffffff", cardText: "#000000", cardBorder: "#84cc16", sajdah: "#d97706", highlightText: "#84cc16", verseBracket: "#831843" },
    
    // --- المجموعة الثانية (الثيمات الداكنة) ---
    deep_black: { id: "deep_black", name: "اسود غامق", bg: "#000000", text: "#ffffff", font: "var(--font-amiri)", barBg: "#000000", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#111111", btnText: "#ffffff", btnBorder: "#10b981", accent: "#10b981", accentText: "#ffffff", modalBg: "#000000", modalText: "#ffffff", headerBg: "#000000", headerText: "#10b981", cardBg: "#0a0a0a", cardText: "#ffffff", cardBorder: "#333333", sajdah: "#10b981", highlightText: "#10b981", verseBracket: "#10b981" },
    i_emerald: { id: "i_emerald", name: "زمرد", bg: "#022c22", text: "#ffffff", font: "var(--font-amiri)", barBg: "#022c22", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#064e3b", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#10b981", accentText: "#ffffff", modalBg: "#022c22", modalText: "#ffffff", headerBg: "#022c22", headerText: "#10b981", cardBg: "#064e3b", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#10b981", verseBracket: "#f87171" },
    i_ruby: { id: "i_ruby", name: "ياقوت", bg: "#450a0a", text: "#ffffff", font: "var(--font-amiri)", barBg: "#450a0a", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#7f1d1d", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#ef4444", accentText: "#ffffff", modalBg: "#450a0a", modalText: "#ffffff", headerBg: "#450a0a", headerText: "#ef4444", cardBg: "#7f1d1d", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#ef4444", verseBracket: "#60a5fa" },
    i_lapis: { id: "i_lapis", name: "لازورد", bg: "#1e3a8a", text: "#ffffff", font: "var(--font-amiri)", barBg: "#1e3a8a", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#3b82f6", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#60a5fa", accentText: "#ffffff", modalBg: "#1e3a8a", modalText: "#ffffff", headerBg: "#1e3a8a", headerText: "#60a5fa", cardBg: "#3b82f6", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#60a5fa", verseBracket: "#fbbf24" },
    i_gold: { id: "i_gold", name: "ذهبي", bg: "#422006", text: "#ffffff", font: "var(--font-amiri)", barBg: "#422006", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#78350f", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#fbbf24", accentText: "#ffffff", modalBg: "#422006", modalText: "#ffffff", headerBg: "#422006", headerText: "#fbbf24", cardBg: "#78350f", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#fbbf24", verseBracket: "#34d399" },
    i_amber: { id: "i_amber", name: "عنبر", bg: "#78350f", text: "#ffffff", font: "var(--font-amiri)", barBg: "#78350f", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#92400e", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#f59e0b", accentText: "#ffffff", modalBg: "#78350f", modalText: "#ffffff", headerBg: "#78350f", headerText: "#f59e0b", cardBg: "#92400e", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#f59e0b", verseBracket: "#60a5fa" },
    i_amethyst: { id: "i_amethyst", name: "أرجوان", bg: "#4c1d95", text: "#ffffff", font: "var(--font-amiri)", barBg: "#4c1d95", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#5b21b6", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#a78bfa", accentText: "#ffffff", modalBg: "#4c1d95", modalText: "#ffffff", headerBg: "#4c1d95", headerText: "#a78bfa", cardBg: "#5b21b6", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#a78bfa", verseBracket: "#34d399" },
    i_sunset_royal: { id: "i_sunset_royal", name: "ملك الغروب", bg: "#280a1e", text: "#ffffff", font: "var(--font-amiri)", barBg: "#280a1e", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#3b102c", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#fbbf24", accentText: "#000000", modalBg: "#280a1e", modalText: "#ffffff", headerBg: "#280a1e", headerText: "#fbbf24", cardBg: "#3b102c", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#fbbf24", verseBracket: "#fbbf24" },
    i_deep_ocean: { id: "i_deep_ocean", name: "ملك الأعماق", bg: "#041e3a", text: "#ffffff", font: "var(--font-amiri)", barBg: "#041e3a", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#062c54", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#22d3ee", accentText: "#000000", modalBg: "#041e3a", modalText: "#ffffff", headerBg: "#041e3a", headerText: "#22d3ee", cardBg: "#062c54", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#22d3ee", verseBracket: "#fbbf24" },
    i_brocade: { id: "i_brocade", name: "إستبرق", bg: "#1e1b4b", text: "#ffffff", font: "var(--font-amiri)", barBg: "#1e1b4b", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#312e81", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#eab308", accentText: "#ffffff", modalBg: "#1e1b4b", modalText: "#ffffff", headerBg: "#1e1b4b", headerText: "#eab308", cardBg: "#312e81", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#eab308", verseBracket: "#60a5fa" },
    i_musk: { id: "i_musk", name: "مسك", bg: "#1c1917", text: "#ffffff", font: "var(--font-amiri)", barBg: "#1c1917", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#292524", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#fbbf24", accentText: "#000000", modalBg: "#1c1917", modalText: "#ffffff", headerBg: "#1c1917", headerText: "#fbbf24", cardBg: "#292524", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#fbbf24", verseBracket: "#f87171" },
    i_midnight: { id: "i_midnight", name: "ليل", bg: "#0f172a", text: "#ffffff", font: "var(--font-amiri)", barBg: "#0f172a", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#1e293b", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#38bdf8", accentText: "#ffffff", modalBg: "#0f172a", modalText: "#ffffff", headerBg: "#0f172a", headerText: "#38bdf8", cardBg: "#1e293b", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#38bdf8", verseBracket: "#fbbf24" },
    i_obsidian: { id: "i_obsidian", name: "بركان", bg: "#09090b", text: "#ffffff", font: "var(--font-amiri)", barBg: "#09090b", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#18181b", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#71717a", accentText: "#ffffff", modalBg: "#09090b", modalText: "#ffffff", headerBg: "#09090b", headerText: "#71717a", cardBg: "#18181b", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#71717a", verseBracket: "#fbbf24" },
    i_forest: { id: "i_forest", name: "غابة", bg: "#064e3b", text: "#ffffff", font: "var(--font-amiri)", barBg: "#064e3b", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#059669", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#10b981", accentText: "#ffffff", modalBg: "#064e3b", modalText: "#ffffff", headerBg: "#064e3b", headerText: "#10b981", cardBg: "#059669", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#10b981", verseBracket: "#fbbf24" },
    i_turquoise: { id: "i_turquoise", name: "فيروزي داكن", bg: "#134e4a", text: "#ffffff", font: "var(--font-amiri)", barBg: "#134e4a", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#14b8a6", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#2dd4bf", accentText: "#ffffff", modalBg: "#134e4a", modalText: "#ffffff", headerBg: "#134e4a", headerText: "#2dd4bf", cardBg: "#14b8a6", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#2dd4bf", verseBracket: "#fbbf24" },
    i_slate: { id: "i_slate", name: "حجري", bg: "#334155", text: "#ffffff", font: "var(--font-amiri)", barBg: "#334155", barText: "#ffffff", barBorder: "#ffffff", btnBg: "#475569", btnText: "#ffffff", btnBorder: "#ffffff", accent: "#94a3b8", accentText: "#ffffff", modalBg: "#334155", modalText: "#ffffff", headerBg: "#334155", headerText: "#94a3b8", cardBg: "#475569", cardText: "#ffffff", cardBorder: "#ffffff", sajdah: "#d97706", highlightText: "#94a3b8", verseBracket: "#fbbf24" }
};
export const READERS = [
    { id: 'Ibrahim_Akhdar_32kbps', name: 'إبراهيم الأخضر' },
    { id: 'Abu_Bakr_Ash-Shaatree_128kbps', name: 'أبو بكر الشاطري' },
    { id: 'Ahmed_ibn_Ali_al-Ajamy_128kbps_ketaballah.net', name: 'أحمد بن علي العجمي' },
    { id: 'Ahmed_Neana_128kbps', name: 'أحمد نعينع' },
    { id: 'Akram_AlAlaqimy_128kbps', name: 'أكرم العلاقمي' },
    { id: 'Ayman_Sowaid_64kbps', name: 'أيمن سويد' },
    { id: 'Khaalid_Abdullaah_al-Qahtaanee_192kbps', name: 'خالد القحطاني' },
    { id: 'khalefa_al_tunaiji_64kbps', name: 'خليفة الطنيجي' },
    { id: 'Ghamadi_40kbps', name: 'سعد الغامدي' },
    { id: 'Saood%20bin%20Ibraaheem%20Ash-Shuraym_128kbps', name: 'سعود الشريم' },
    { id: 'Sahl_Yassin_128kbps', name: 'سهل ياسين' },
    { id: 'Parhizgar_48kbps', name: 'شهريار بارهيزجار' },
    { id: 'Salah_Al_Budair_128kbps', name: 'صلاح البدير' },
    { id: 'Salaah_AbdulRahman_Bukhatir_128kbps', name: 'صلاح بو خاطر' },
    { id: 'Abdul_Basit_Mujawwad_128kbps', name: 'عبدالباسط عبدالصمد مجود' },
    { id: 'Abdul_Basit_Murattal_192kbps', name: 'عبدالباسط عبدالصمد مرتل' },
    { id: 'Abdurrahmaan_As-Sudais_192kbps', name: 'عبدالرحمن السديس' },
    { id: 'Abdullah_Basfar_192kbps', name: 'عبدالله بصفر' },
    { id: 'Abdullah_Matroud_128kbps', name: 'عبدالله مطرود' },
    { id: 'aziz_alili_128kbps', name: 'عزيز عليلي' },
    { id: 'Hudhaify_128kbps', name: 'علي الحذيفي' },
    { id: 'Ali_Jaber_64kbps', name: 'علي جابر' },
    { id: 'Ali_Hajjaj_AlSuesy_128kbps', name: 'علي حجاج السويسي' },
    { id: 'Fares_Abbad_64kbps', name: 'فارس عباد' },
    { id: 'Karim_Mansoori_40kbps', name: 'كريم منصوري' },
    { id: 'MaherAlMuaiqly128kbps', name: 'ماهر المعيقلي' },
    { id: 'Muhsin_Al_Qasim_192kbps', name: 'محسن القاسم' },
    { id: 'Muhammad_Ayyoub_128kbps', name: 'محمد أيوب' },
    { id: 'Muhammad_Jibreel_128kbps', name: 'محمد جبريل' },
    { id: 'Minshawy_Mujawwad_192kbps', name: 'محمد صديق المنشاوي مجود' },
    { id: 'Minshawy_Murattal_128kbps', name: 'محمد صديق المنشاوي مرتل' },
    { id: 'Minshawy_Teacher_128kbps', name: 'محمد صديق المنشاوي معلم' },
    { id: 'Muhammad_AbdulKareem_128kbps', name: 'محمد عبدالكريم' },
    { id: 'Mohammad_al_Tablaway_128kbps', name: 'محمود الطبلاوي' },
    { id: 'Husary_128kbps', name: 'محمود خليل الحصري' },
    { id: 'Husary_128kbps_Mujawwad', name: 'محمود خليل الحصري مجود' },
    { id: 'Husary_Muallim_128kbps', name: 'محمود خليل الحصري معلم' },
    { id: 'mahmoud_ali_al_banna_32kbps', name: 'محمود علي البنا' },
    { id: 'Alafasy_128kbps', name: 'مشاري العفاسي' },
    { id: 'Mustafa_Ismail_48kbps', name: 'مصطفى إسماعيل' },
    { id: 'Nasser_Alqatami_128kbps', name: 'ناصر القطامي' },
    { id: 'Nabil_Rifa3i_48kbps', name: 'نبيل الرفاعي' },
    { id: 'Hani_Rifai_192kbps', name: 'هاني الرفاعي' },
    { id: 'Yasser_Ad-Dussary_128kbps', name: 'ياسر الدوسري' },
    { id: 'Yaser_Salamah_128kbps', name: 'ياسر سلامة' }
];
export const MEMORIZATION_READERS = [
    { id: 'Ibrahim_Akhdar_32kbps', name: 'إبراهيم الأخضر' },
    { id: 'Abu_Bakr_Ash-Shaatree_128kbps', name: 'أبو بكر الشاطري' },
    { id: 'Ahmed_ibn_Ali_al-Ajamy_128kbps_ketaballah.net', name: 'أحمد بن علي العجمي' },
    { id: 'Ahmed_Neana_128kbps', name: 'أحمد نعينع' },
    { id: 'Akram_AlAlaqimy_128kbps', name: 'أكرم العلاقمي' },
    { id: 'Ayman_Sowaid_64kbps', name: 'أيمن سويد' },
    { id: 'Khaalid_Abdullaah_al-Qahtaanee_192kbps', name: 'خالد القحطاني' },
    { id: 'khalefa_al_tunaiji_64kbps', name: 'خليفة الطنيجي' },
    { id: 'Ghamadi_40kbps', name: 'سعد الغامدي' },
    { id: 'Saood%20bin%20Ibraaheem%20Ash-Shuraym_128kbps', name: 'سعود الشريم' },
    { id: 'Sahl_Yassin_128kbps', name: 'سهل ياسين' },
    { id: 'Parhizgar_48kbps', name: 'شهريار بارهيزجار' },
    { id: 'Salah_Al_Budair_128kbps', name: 'صلاح البدير' },
    { id: 'Salaah_AbdulRahman_Bukhatir_128kbps', name: 'صلاح بو خاطر' },
    { id: 'Abdul_Basit_Mujawwad_128kbps', name: 'عبدالباسط عبدالصمد مجود' },
    { id: 'Abdul_Basit_Murattal_192kbps', name: 'عبدالباسط عبدالصمد مرتل' },
    { id: 'Abdurrahmaan_As-Sudais_192kbps', name: 'عبدالرحمن السديس' },
    { id: 'Abdullah_Basfar_192kbps', name: 'عبدالله بصفر' },
    { id: 'Abdullah_Matroud_128kbps', name: 'عبدالله مطرود' },
    { id: 'aziz_alili_128kbps', name: 'عزيز عليلي' },
    { id: 'Hudhaify_128kbps', name: 'علي الحذيفي' },
    { id: 'Ali_Jaber_64kbps', name: 'علي جابر' },
    { id: 'Ali_Hajjaj_AlSuesy_128kbps', name: 'علي حجاج السويسي' },
    { id: 'Fares_Abbad_64kbps', name: 'فارس عباد' },
    { id: 'Karim_Mansoori_40kbps', name: 'كريم منصوري' },
    { id: 'MaherAlMuaiqly128kbps', name: 'ماهر المعيقلي' },
    { id: 'Muhsin_Al_Qasim_192kbps', name: 'محسن القاسم' },
    { id: 'Muhammad_Ayyoub_128kbps', name: 'محمد أيوب' },
    { id: 'Muhammad_Jibreel_128kbps', name: 'محمد جبريل' },
    { id: 'Minshawy_Mujawwad_192kbps', name: 'محمد صديق المنشاوي مجود' },
    { id: 'Minshawy_Murattal_128kbps', name: 'محمد صديق المنشاوي مرتل' },
    { id: 'Minshawy_Teacher_128kbps', name: 'محمد صديق المنشاوي معلم' },
    { id: 'Muhammad_AbdulKareem_128kbps', name: 'محمد عبدالكريم' },
    { id: 'Mohammad_al_Tablaway_128kbps', name: 'محمود الطبلاوي' },
    { id: 'Husary_128kbps', name: 'محمود خليل الحصري' },
    { id: 'Husary_128kbps_Mujawwad', name: 'محمود خليل الحصري مجود' },
    { id: 'Husary_Muallim_128kbps', name: 'محمود خليل الحصري معلم' },
    { id: 'mahmoud_ali_al_banna_32kbps', name: 'محمود علي البنا' },
    { id: 'Alafasy_128kbps', name: 'مشاري العفاسي' },
    { id: 'Mustafa_Ismail_48kbps', name: 'مصطفى إسماعيل' },
    { id: 'Nasser_Alqatami_128kbps', name: 'ناصر القطامي' },
    { id: 'Nabil_Rifa3i_48kbps', name: 'نبيل الرفاعي' },
    { id: 'Hani_Rifai_192kbps', name: 'هاني الرفاعي' },
    { id: 'Yasser_Ad-Dussary_128kbps', name: 'ياسر الدوسري' },
    { id: 'Yaser_Salamah_128kbps', name: 'ياسر سلامة' }
];
export const TAFSEERS = [{ id: 'ar.jalalayn', name: 'تفسير الجلالين' }, { id: 'ar.muyassar', name: 'التفسير الميسر' }, { id: 'ar.baghawi', name: 'تفسير البغوي' }, { id: 'ar.qurtubi', name: 'تفسير القرطبي' }, { id: 'ar.waseet', name: 'التفسير الوسيط' }];

export const FONTS = [
    { id: "var(--font-amiri)", name: "نسخ" },
    { id: "var(--font-noto)", name: "نسخ حديث" },
    { id: "var(--font-lateef)", name: "تراثي" },
    { id: "var(--font-thuluth)", name: "ثلوث" },
    { id: "var(--font-aref)", name: "رقعة" },
    { id: "var(--font-harmattan)", name: "ورش" },
    { id: "var(--font-amiri-quran)", name: "حفص" },
    { id: "'Me Quran'", name: "خط المصحف" },
    { id: "var(--font-katibeh)", name: "قطيبة" },
    { id: "var(--font-qalam)", name: "قلم" },
    { id: "var(--font-kufi)", name: "كوفي" },
    { id: "'KFGQPC Uthman Taha Naskh'", name: "مجمع الملك فهد" },
    { id: "var(--font-scheherazade)", name: "مجود" },
    { id: "var(--font-mirza)", name: "ميرزا" }
].sort((a, b) => a.name.localeCompare(b.name, 'ar'));

export const SURAH_INFO: Record<number, { ayahs: number, type: string }> = {
    1: { ayahs: 7, type: "مكية" },
    2: { ayahs: 286, type: "مدنية" },
    3: { ayahs: 200, type: "مدنية" },
    4: { ayahs: 176, type: "مدنية" },
    5: { ayahs: 120, type: "مدنية" },
    6: { ayahs: 165, type: "مكية" },
    7: { ayahs: 206, type: "مكية" },
    8: { ayahs: 75, type: "مدنية" },
    9: { ayahs: 129, type: "مدنية" },
    10: { ayahs: 109, type: "مكية" },
    11: { ayahs: 123, type: "مكية" },
    12: { ayahs: 111, type: "مكية" },
    13: { ayahs: 43, type: "مدنية" },
    14: { ayahs: 52, type: "مكية" },
    15: { ayahs: 99, type: "مكية" },
    16: { ayahs: 128, type: "مكية" },
    17: { ayahs: 111, type: "مكية" },
    18: { ayahs: 110, type: "مكية" },
    19: { ayahs: 98, type: "مكية" },
    20: { ayahs: 135, type: "مكية" },
    21: { ayahs: 112, type: "مكية" },
    22: { ayahs: 78, type: "مدنية" },
    23: { ayahs: 118, type: "مكية" },
    24: { ayahs: 64, type: "مدنية" },
    25: { ayahs: 77, type: "مكية" },
    26: { ayahs: 227, type: "مكية" },
    27: { ayahs: 93, type: "مكية" },
    28: { ayahs: 88, type: "مكية" },
    29: { ayahs: 69, type: "مكية" },
    30: { ayahs: 60, type: "مكية" },
    31: { ayahs: 34, type: "مكية" },
    32: { ayahs: 30, type: "مكية" },
    33: { ayahs: 73, type: "مدنية" },
    34: { ayahs: 54, type: "مكية" },
    35: { ayahs: 45, type: "مكية" },
    36: { ayahs: 83, type: "مكية" },
    37: { ayahs: 182, type: "مكية" },
    38: { ayahs: 88, type: "مكية" },
    39: { ayahs: 75, type: "مكية" },
    40: { ayahs: 85, type: "مكية" },
    41: { ayahs: 54, type: "مكية" },
    42: { ayahs: 53, type: "مكية" },
    43: { ayahs: 89, type: "مكية" },
    44: { ayahs: 59, type: "مكية" },
    45: { ayahs: 37, type: "مكية" },
    46: { ayahs: 35, type: "مكية" },
    47: { ayahs: 38, type: "مدنية" },
    48: { ayahs: 29, type: "مدنية" },
    49: { ayahs: 18, type: "مدنية" },
    50: { ayahs: 45, type: "مكية" },
    51: { ayahs: 60, type: "مكية" },
    52: { ayahs: 49, type: "مكية" },
    53: { ayahs: 62, type: "مكية" },
    54: { ayahs: 55, type: "مكية" },
    55: { ayahs: 78, type: "مدنية" },
    56: { ayahs: 96, type: "مكية" },
    57: { ayahs: 29, type: "مدنية" },
    58: { ayahs: 22, type: "مدنية" },
    59: { ayahs: 24, type: "مدنية" },
    60: { ayahs: 13, type: "مدنية" },
    61: { ayahs: 14, type: "مدنية" },
    62: { ayahs: 11, type: "مدنية" },
    63: { ayahs: 11, type: "مدنية" },
    64: { ayahs: 18, type: "مدنية" },
    65: { ayahs: 12, type: "مدنية" },
    66: { ayahs: 12, type: "مدنية" },
    67: { ayahs: 30, type: "مكية" },
    68: { ayahs: 52, type: "مكية" },
    69: { ayahs: 52, type: "مكية" },
    70: { ayahs: 44, type: "مكية" },
    71: { ayahs: 28, type: "مكية" },
    72: { ayahs: 28, type: "مكية" },
    73: { ayahs: 20, type: "مكية" },
    74: { ayahs: 56, type: "مكية" },
    75: { ayahs: 40, type: "مكية" },
    76: { ayahs: 31, type: "مدنية" },
    77: { ayahs: 50, type: "مكية" },
    78: { ayahs: 40, type: "مكية" },
    79: { ayahs: 46, type: "مكية" },
    80: { ayahs: 42, type: "مكية" },
    81: { ayahs: 29, type: "مكية" },
    82: { ayahs: 19, type: "مكية" },
    83: { ayahs: 36, type: "مكية" },
    84: { ayahs: 25, type: "مكية" },
    85: { ayahs: 22, type: "مكية" },
    86: { ayahs: 17, type: "مكية" },
    87: { ayahs: 19, type: "مكية" },
    88: { ayahs: 26, type: "مكية" },
    89: { ayahs: 30, type: "مكية" },
    90: { ayahs: 20, type: "مكية" },
    91: { ayahs: 15, type: "مكية" },
    92: { ayahs: 21, type: "مكية" },
    93: { ayahs: 11, type: "مكية" },
    94: { ayahs: 8, type: "مكية" },
    95: { ayahs: 8, type: "مكية" },
    96: { ayahs: 19, type: "مكية" },
    97: { ayahs: 5, type: "مكية" },
    98: { ayahs: 8, type: "مدنية" },
    99: { ayahs: 8, type: "مدنية" },
    100: { ayahs: 11, type: "مكية" },
    101: { ayahs: 11, type: "مكية" },
    102: { ayahs: 8, type: "مكية" },
    103: { ayahs: 3, type: "مكية" },
    104: { ayahs: 9, type: "مكية" },
    105: { ayahs: 5, type: "مكية" },
    106: { ayahs: 4, type: "مكية" },
    107: { ayahs: 7, type: "مكية" },
    108: { ayahs: 3, type: "مكية" },
    109: { ayahs: 6, type: "مكية" },
    110: { ayahs: 3, type: "مدنية" },
    111: { ayahs: 5, type: "مكية" },
    112: { ayahs: 4, type: "مكية" },
    113: { ayahs: 5, type: "مكية" },
    114: { ayahs: 6, type: "مكية" }
};

export const SURAH_NAMES_AR = [
    "الفاتحة", "البقرة", "آل عمران", "النساء", "المائدة", "الأنعام", "الأعراف", "الأنفال", "التوبة", "يونس",
    "هود", "يوسف", "الرعد", "إبراهيم", "الحجر", "النحل", "الإسراء", "الكهف", "مريم", "طه",
    "الأنبياء", "الحج", "المؤمنون", "النور", "الفرقان", "الشعراء", "النمل", "القصص", "العنكبوت", "الروم",
    "لقمان", "السجدة", "الأحزاب", "سبأ", "فاطر", "يس", "الصافات", "ص", "الزمر", "غافر",
    "فصلت", "الشورى", "الزخرف", "الدخان", "الجاثية", "الأحقاف", "محمد", "الفتح", "الحجرات", "ق",
    "الذاريات", "الطور", "النجم", "القمر", "الرحمن", "الواقعة", "الحديد", "المجادلة", "الحشر", "الممتحنة",
    "الصف", "الجمعة", "المنافقون", "التغابن", "الطلاق", "التحريم", "الملك", "القلم", "الحاقة", "المعارج",
    "نوح", "الجن", "المزمل", "المدثر", "القيامة", "الإنسان", "المرسلات", "النبأ", "النازعات", "عبس",
    "التكوير", "الانفطار", "المطففين", "الانشقاق", "البروج", "الطارق", "الأعلى", "الغاشية", "الفجر", "البلد",
    "الشمس", "الليل", "الضحى", "الشرح", "التين", "العلق", "القدر", "البينة", "الزلزلة", "العاديات",
    "القارعة", "التكاثر", "العصر", "الهمزة", "الفيل", "قريش", "الماعون", "الكوثر", "الكافرون", "النصر",
    "المسد", "الإخلاص", "الفلق", "الناس"
];

export const toArabic = (n: number | string) => String(n).replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[+d]);

export const getAyahCountText = (count: number) => {
    const arabicCount = toArabic(count);
    const lastTwo = count % 100;
    if (count === 0) return `٠ آية`;
    // Arabic grammar: 3-10 uses plural "Ayat", others use singular "Ayah"
    if (lastTwo >= 3 && lastTwo <= 10) return `${arabicCount} آيات`;
    return `${arabicCount} آية`;
};

export const DEFAULT_SETTINGS = {
    fontSize: 1.7,
    fontFamily: "var(--font-amiri)",
    isBold: false,
    textColor: "",
    bgColor: "",
    highlightTextColor: "#10b981",
    reader: 'Abu_Bakr_Ash-Shaatree_128kbps',
    theme: 'black',
    scrollMinutes: 20,
    tafseer: 'ar.jalalayn',
    lockHighlightColor: false,
    ayahRepeatCount: 1,
    showPageBorder: false,
    surahHeaderDesign: 1
};
